version: "3.9"

services:
  arangoDb:
    image: arangodb:latest
    restart: unless-stopped
    environment:
      #user-name is root  
      - ARANGO_ROOT_PASSWORD=rezareza
    ports:
      - 8529:8529
    container_name: nims-dbs-arangoDb
    
    #  database.init-database
    #command: arangosh --server.password rezareza
    #command: arangosh --server.endpoint tcp://127.0.0.1:8529 --server.username root --server.password rezareza
    #--database.init-database 
    #command: apk update & apk upgrade & apk add bash & bash -c "arangosh --server.username root --server.password rezareza"
    # && db._createDatabase("nims")

  influxDb:
    image: influxdb:latest
    command: influxd
    restart: unless-stopped
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=rezareza
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket1
    ports:
      - 8086:8086
    container_name: nims-dbs-influxDb

  nims-core-mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1884:1884
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  
networks:
  default:
    name: 'nims'
    external: true

  # data-collector:
  #   image: rezaaslani/nims-data-collector
  #   restart: unless-stopped
  #   depends_on:
  #     - arangoDb
  #     - influxDb
  #     - nims-core-mosquitto

  # dev-simulator:
  #   image: rezaaslani/nims-dev-simulator 
  #   restart: unless-stopped
  #   depends_on:
  #     - nims-core-mosquitto

# volumes:
#   nims-dbs-volume1:
#   nims-dbs-volume2:
  
